CREATE TABLE Users (
  UserId INT PRIMARY KEY IDENTITY(1,1),
  FirstName VARCHAR(50) NULL,
  LastName VARCHAR(50) NULL,
  Email VARCHAR(255) NULL,
  PhoneNumber VARCHAR(20),
  BusinessId INT NULL,
  PasswordHash VARBINARY(256) NULL,
  Salt VARBINARY(16) NULL,
  CreatedAt DATETIME NULL DEFAULT GETDATE(),
  UpdatedAt DATETIME NULL DEFAULT GETDATE()
);